version: '3.8'

services:
  app:
    image: sciohub/summary-generator:${ENV}
    container_name: summary-generator
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]